- sample/script.js
- src/htmlContents/noBalanceHTML.ts
- src/main.ts
- src/scriptContents/noBalanceScript.ts
> fix: close popup and prevent popup in mobile

- sample/index.html
- src/main.ts
- src/scriptContents/noBalanceScript.ts
- src/utils/portfolio.ts
> Changed accessing of imports in html strings, fixed contract decimals issue in bridge quote

- package-lock.json
- src/htmlContents/bridgeLoadingHTML.ts
- src/htmlContents/bridgeSuccessHTML.ts
- src/htmlContents/switchBackHTML.ts
- src/main.ts
- src/scriptContents/noBalanceScript.ts
> Added minimizing and maximizing of window after bridge deposit

- src/htmlContents/bridgeLoadingHTML.ts
> increased clickable area for minimise icon

- src/htmlContents/bridgeInputHTML.ts
- src/htmlContents/bridgeLoadingHTML.ts
- src/htmlContents/bridgeSuccessHTML.ts
- src/htmlContents/noBalanceHTML.ts
- src/htmlContents/switchBackHTML.ts
- src/scriptContents/noBalanceScript.ts
> Changed minimizing of bridge loading screen

- esbuild.browser.config.js
- sample/index.html
- src/htmlContents/bridgeInputHTML.ts
- src/htmlContents/bridgeLoadingHTML.ts
- src/htmlContents/bridgeSuccessHTML.ts
- src/htmlContents/bridgeSummaryHTML.ts
- src/htmlContents/bridgeSwitchHTML.ts
- src/htmlContents/noBalanceHTML.ts
- src/htmlContents/portfolioLoadingHTML.ts
- src/htmlContents/switchBackHTML.ts
- src/main.ts
- src/scriptContents/noBalanceScript.ts
Screen Recording 2023-04-26 at 3.12.48 PM.mov
> Feat inital loader

- sample/index.html
- src/scriptContents/noBalanceScript.ts
> fix: console logs removal

- src/cssContents/noBalanceCSS.ts
- src/htmlContents/noBalanceHTML.ts
> fix: noBalanceHTML height

- src/main.ts
> fix: multiple popup trigger

- src/cssContents/noBalanceCSS.ts
- src/htmlContents/bridgeInputHTML.ts
- src/htmlContents/bridgeLoadingHTML.ts
- src/htmlContents/bridgeSuccessHTML.ts
- src/htmlContents/bridgeSummaryHTML.ts
- src/htmlContents/bridgeSwitchHTML.ts
- src/htmlContents/noBalanceHTML.ts
- src/htmlContents/switchBackHTML.ts
- src/main.ts
- src/scriptContents/noBalanceScript.ts
> responsiveness

- sample/index.html
- src/cssContents/noBalanceCSS.ts
- src/htmlContents/bridgeInputHTML.ts
- src/htmlContents/bridgeLoadingHTML.ts
- src/htmlContents/bridgeSuccessHTML.ts
- src/htmlContents/bridgeSummaryHTML.ts
- src/htmlContents/bridgeSwitchHTML.ts
- src/htmlContents/noBalanceHTML.ts
- src/htmlContents/portfolioLoadingHTML.ts
- src/htmlContents/switchBackHTML.ts
- src/scriptContents/noBalanceScript.ts
> viewport fix

- src/htmlContents/bridgeLoadingHTML.ts
- src/htmlContents/noBalanceHTML.ts
- src/htmlContents/portfolioLoadingHTML.ts
> responsiveness-fix

- sample/index.html
- src/cssContents/noBalanceCSS.ts
- src/htmlContents/bridgeInputHTML.ts
- src/htmlContents/bridgeLoadingHTML.ts
- src/htmlContents/bridgeSuccessHTML.ts
- src/htmlContents/bridgeSummaryHTML.ts
- src/htmlContents/bridgeSwitchHTML.ts
- src/htmlContents/noBalanceHTML.ts
- src/htmlContents/portfolioLoadingHTML.ts
- src/htmlContents/switchBackHTML.ts
- src/main.ts
- src/scriptContents/noBalanceScript.ts
> Changed style to accommodate viewport for mobile screen sizes

- src/core/portfolio.ts
- src/htmlContents/noBalanceHTML.ts
- src/main.ts
> Moved minimum bridgeable balance check to UI

- sample/index.html
- src/cssContents/noBalanceCSS.ts
- src/htmlContents/noBalanceHTML.ts
- src/interface/dappDetails.interface.ts
- src/main.ts
- src/utils/portfolio.ts
> info screen

- src/constants/server.ts
- src/core/bridge.ts
- src/core/clickHandler.ts
- src/core/handlerFunctions.ts
- src/main.ts
- src/screens/emptyWallet.ts
- src/screens/index.ts
- src/screens/infoScreen.ts
- src/screens/portfolioBalance.ts
> fix: destructuring

- src/constants/server.ts
- src/core/bridge.ts
- src/core/send.ts
- src/utils/utilFunctions.ts
> fallback: changes

- src/screens/bridgeSuccess.ts
> fix: padding in succes screen

- src/core/portfolio.ts
- src/main.ts
- src/screens/bridgeSuccess.ts
> Fixed auto trigering of sdk

- src/constants/server.ts
- src/screens/bridgeInput.ts
- src/screens/bridgeSuccess.ts
- src/screens/bridgeSummary.ts
- src/screens/emptyWallet.ts
- src/screens/portfolioBalance.ts
- src/screens/switchChain.ts
> feat: dummy token img + chain & token design

- src/constants/server.ts
> changed rpc url for eth

- src/constants/server.ts
> Avoided displaying of required token in tokens list

- src/main.ts
- Tailwind loader function returning a promise
> local: tailwind loading fix

- .gitignore
- cypress/e2e/bridgeInput.cy.ts
- cypress/e2e/bridgeLoading.cy.ts
- cypress/e2e/bridgeSuccess.cy.ts
- cypress/e2e/bridgeSummary.cy.ts
- cypress/e2e/footer.cy.ts
- cypress/e2e/home.cy.ts
- cypress/e2e/onGoingBridge.cy.ts
- cypress/e2e/portfolio.cy.ts
- cypress/e2e/portfolioLoading.cy.ts
- cypress/e2e/swap.cy.ts
- cypress/e2e/switchChain.cy.ts
- sample/indexTest.html
> test: fixes

- .github/workflows/main.yml
- cypress/e2e/bridgeInput.cy.ts
- cypress/e2e/bridgeLoading.cy.ts
- cypress/e2e/bridgeSuccess.cy.ts
- cypress/e2e/bridgeSummary.cy.ts
- cypress/e2e/footer.cy.ts
- cypress/e2e/home.cy.ts
- cypress/e2e/onGoingBridge.cy.ts
- cypress/e2e/portfolio.cy.ts
- cypress/e2e/portfolioLoading.cy.ts
- cypress/e2e/swap.cy.ts
- cypress/e2e/switchChain.cy.ts
> fix: test changes reverted

- cypress/e2e/bridgeInput.cy.ts
- cypress/e2e/bridgeLoading.cy.ts
- cypress/e2e/bridgeSummary.cy.ts
- cypress/e2e/exchangeWidget.cy.ts
- cypress/e2e/onGoingBridge.cy.ts
- cypress/e2e/portfolio.cy.ts
- cypress/e2e/portfolioLoading.cy.ts
- src/components/chainDropdown.ts
- src/components/tokenDropdown.ts
- src/core/handlerFunctions.ts
- src/cssContents/noBalanceCSS.ts
- src/screens/exchangeWidget.ts
- src/utils/container.ts
- src/utils/utilFunctions.ts
- test/sdkTest.html
- test/web3MockOnSdk.js
> widget-test

- src/core/bridge.ts
- src/core/handlerFunctions.ts
- src/main.ts
> cypher-call

- src/main.ts
- src/screens/emptyWallet.ts
- src/screens/switchChain.ts
> fix: widget empty-wallet

- src/main.ts
- src/screens/emptyWalletSDK.ts
- src/screens/index.ts
- test/sdkTest.html
> changed text in empty wallet screen SDK (#89)

- src/constants/server.ts
- src/core/clickHandler.ts
- src/core/portfolio.ts
- src/interface/walletHoldings.interface.ts
- src/screens/portfolioBalance.ts
- src/utils/portfolio.ts
> Support L2 chains base, era, zkevm

- src/constants/server.ts
- src/core/clickHandler.ts
- src/core/portfolio.ts
- src/interface/walletHoldings.interface.ts
- src/screens/portfolioBalance.ts
- src/utils/portfolio.ts
> Support L2 chains base, era, zkevm (#93)

- src/main.ts
- src/screens/bridgeSuspended.ts
> Disabled bridge temporarily

- README.md
- src/main.ts
- src/screens/bridgeSuspended.ts
> Temporarily disabled bridge

- sample/indexTest.html
- src/main.ts
> Added killing of previous instance when new window.cypher call is made
